### ISSUE TITLE
Upgrade Prometheus operator

### ISSUE THREAD

**Issue by AndersBennedsgaard** [neticdk/k8s-oaas-observability#135]
The latest Prometheus operator is currently in version 0.68.0 (https://github.com/prometheus-operator/prometheus-operator/releases), while https://github.com/neticdk/k8s-oaas-observability/tree/main/charts/prometheus-operator is only in v0.56.1 which is over a year old.

Therefore, you include several CVEs which have been closed upstream, missing several new CRDs, and other enhancements such as performance and functionality features

**Comment by langecode** [comment]
I thought we had fixed this with the recent introduction of renovate - however it does not seem to be the case. I have made an overhaul of the prometheus-operator chart and it should also now be part of the renovate configuration to be kept up to date.
